services:
  public:
    build: './src/public'
    ports:
      - '8080:80'
    volumes:
      - './src/public:/usr/share/nginx/html'
  app:
    build: ./src/app
    ports:
      - '80:80'
    volumes:
      - './src/app:/app'
